add stored-atom
adrianmroz/rx-atom pull request #1
Opened 2017-06-21 20:38 UTC by adrianmroz

2017-06-21 21:11 UTC, bigsergey commented on src/lensed-atom.ts
> +  }
empty constructor? is it okey?

2017-06-22 05:07 UTC, erykpiast commented on src/lensed-atom.ts
> +  }
It's not empty actually. `(private lens: Lens, private source: Atom<S>)` part sets two private properties on class instance (named as arguments: `lens` and `source`). TypeScript magic ;)

2017-06-22 05:24 UTC, erykpiast requested changes
How could you refactor without any tests? :P

2017-06-22 05:24 UTC, erykpiast commented on src/atom.ts
> +export interface IAtom<T> {
I would say, this declaration could be moved to separate file along with `Modifier` and `Projection` types, as those two may feel a bit lonely.

2017-06-22 05:24 UTC, erykpiast commented on src/stored-atom.ts
> +    super(savedItem === null ? defaultValue : from(JSON.parse(savedItem)));
`savedItem === null ? defaultValue : from(JSON.parse(savedItem))` name it

2017-06-22 05:24 UTC, erykpiast commented on src/stored-atom.ts
> +    super(savedItem === null ? defaultValue : from(JSON.parse(savedItem)));
I'd say this one: `from(JSON.parse(savedItem))` should be called `parse` and this `SON.stringify(to(value))` - `serialize`. They may be just functions in constructor scope, but named ones. If you do that expression like `savedItem === null ? defaultValue : parse(savedItem)` is clear enough to have no name.

2017-06-22 05:24 UTC, erykpiast commented on index.ts
> +import { Atom as AtomDef } from './src/atom';
`export { Atom } from './src/atom'?`

2017-06-22 05:24 UTC, erykpiast commented on src/atom.ts
> +export class Atom<T> implements IAtom<T> {
shouldn't it be default export?

2017-06-22 05:24 UTC, erykpiast commented on src/lensed-atom.ts
> +export class LensedAtom<T, S> implements IAtom<T> {
default export?

2017-06-22 05:24 UTC, erykpiast commented on src/stored-atom.ts
> +  private storedValue$: Observable<T>;
default export?

2017-06-22 05:24 UTC, erykpiast commented on src/stored-atom.ts
> +interface StoredAtomOptions<T> {
If you started with `IName` convention for interfaces, let's stick to it or abandon at all.

2017-06-22 05:24 UTC, erykpiast commented on src/modifier.ts
> +export type Modifier<T> = (value: T) => T;
default export (if you don't gonna merge it with `projection.ts`)

2017-06-22 05:24 UTC, erykpiast commented on src/projection.ts
> +export type Projection<T, R> = (source: T) => R;
as above

2017-06-27 19:44 UTC, merged